# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: gl:openscm/copier-basic-python-repository
email: zebedee.nicholls@climate-resource.com
name: Zebedee Nicholls
notebooks: true
package_manager: pixi
project_description_short: Generation of GHG concentration inputs (i.e. forcings)
    for CMIP7's ScenarioMIP.
project_url: https://github.com/climate-resource/cmip7-scenariomip-ghg-concentrations
